#ifndef FRX_VERSION_H
#define FRX_VERSION_H

#define FRX_VERSION_MAJOR 0
#define FRX_VERSION_MINOR 0
#define FRX_VERSION_PATCH 0

#define FRX_STRINGIFY_IMPL(x) #x
#define FRX_STRINGIFY(x) FRX_STRINGIFY_IMPL(x)

#define FRX_VERSION_STR (FRX_STRINGIFY(FRX_VERSION_MAJOR) "." FRX_STRINGIFY(FRX_VERSION_MINOR) "." FRX_STRINGIFY(FRX_VERSION_PATCH))

#endif
